services:
 backend:
  build: ./backend
  image: sergio5212/api-web-simple:latest
  container_name: backend-contactos
  ports:
   - "8000:8000"

 frontend:
  build: ./frontend
  image: sergio5212/aplicacion-web-simple:latest
  container_name: frontend-contactos
  ports:
   - "80:80"